# Push the `website/public` directory to the `gh-pages` branch.
#
# The 'main' branch of this repository is the source of truth for the website content.
#   The gh-pages branch simply exists as a mirror of `website/public` directory
#   of the `main` branch to serve that site content via GitHub pages.
#   The `gh-pages` branch should never be edited directly, and should always be
#   an exact mirror of the `website/public` directory on the `main` branch.
#   This workflow performs that mirror, which then triggers another action
#   on the `gh-pages` branch that deploys the site content to GitHub Pages.

name: Verify the website/src directory builds

# Run whenever the `website/public` folder in the `main` branch changes.
on:
  pull_request:
    branches:
      - "main"
    paths:
      - "website/**"
  # Allow manual runs from the Actions tab
  workflow_dispatch:

jobs:
  build-gh-pages:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
      # Install dependancies
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: cd website && npm install
      # Build the website
      - name: Build
        run: cd website && npm run build
